server:
  port: 9000
  context-path: /job

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jobDB?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/templates
    suffix: .html



mybatis:
  #实体类所做包, 省去了再mapper.xml中的type前
  type-aliases-package: com.job.entity
  #mapper.xml所在位置
  mapper-locations: classpath:mappers/*.xml
